### ISSUE TITLE
Update rust-vmm-ci

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/versionize#29]
The latest update was in September 2020. Since then, we added a few new features to rust-vmm-ci. One that is particularly useful is the one where you can run the coverage test and keep the results locally by running with:
```pytest rust-vmm-ci/integration_tests/test_coverage.py --no-cleanup```

**Comment by andreeaflorescu** [comment]
Guide that we use for updating rust-vmm-ci: https://github.com/rust-vmm/community/blob/master/CONTRIBUTING.md#updating-the-rust-vmm-ci

**Comment by berciuliviu** [comment]
Fixed in #32
